apiVersion: v1
kind: ConfigMap
metadata:
  name: gslb-operator-config
  namespace: {{ .Values.namespace }}
data:
  SRV_ENV: {{ .Values.settings.env }}
  SRV_LUA_SANDBOX: {{ .Values.settings.sandbox }}
  SRV_LOG_LEVEL: {{ .Values.settings.log_level }}
  API_PORT: {{ .Values.settings.port }}
  GSLB_POLL_INTERVAL: {{ .Values.settings.poll_interval }}
  {{- if .Values.webhooks.enable }}
  MQ_ENABLED: true
  MQ_ENDPOINT: {{ .Values.settings.mq_endpoint }}
  MQ_PORT: {{ .Values.settings.mq_port }}
  {{- end}}
  VK_ADDR: {{ .Values.settings.vk_addr}}
