apiVersion: v1
kind: ConfigMap
metadata:
  name: gslb-operator-config
data:
  config.yaml: |
    server:
      env: {{ .Values.env }}
      lua_sandbox: sandbox.lua
      log_level: {{ .Values.logLevel }}

    api:
      port: {{ .Values.settings.port }}

    split_dns:
      enabled: {{ .Values.split_dns.enabled }}
      defaultView: {{ .Values.split_dns.defaultView }}
      views: {{- toYaml .Values.split_dns.views | nindent 8 }}


    gslb:
      status:
        enabled: false
      site: {{ .Values.datacenter }}
      poll_interval: 1m
      {{- with .Values.dnsdist }}
      dnsdist:
        {{- toYaml . | nindent 8 }}
      {{- end }}


    valkey:
      enabled: true
      addr: {{ .Values.settings.vk_addr }}


    {{- if .Values.mq.enabled }}
    mq:
      enabled: true
    {{- end }}

    {{- if .Values.webhooks.enabled }}
    webhooks:
      enabled: true
      notifications:
        slack:
          enabled: false
    {{- end }}
