{{- if .Values.vault.enable }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gslb-operator-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lb-openbao				
    kind: ClusterSecretStore
  target:
    name: gslb-operator-secrets
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: /gslb-operator
        property: jwt-secret
    - secretKey: JWT_USER
      remoteRef:
        key: /gslb-operator
        property: jwt-user
    - secretKey: GSLB_ZONE
      remoteRef:
        key: /gslb-operator
        property: gslb-zone
    - secretKey: GSLB_NAMESERVER
      remoteRef:
        key: /gslb-operator
        property: gslb-nameserver
    {{- if .Values.webhooks.enable}}
    - secretKey: MQ_PASS
      remoteRef: /gslb-operator
      property: mq-pass
    - secretKey: MQ_USER
      remoteRef: /gslb-operator
      property: mq-user
    {{- end}}
    - secretKey: VK_USER
      remoteRef:
        key: /gslb-operator
        property: valkey-user
    - secretKey: VK_PASS
      remoteRef:
        key: /gslb-operator
        property: valkey-pass
{{- end }}
