{{- if .Values.vault.enable }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "gslb-operator.fullname" .}}-external-secret
  
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ include "gslb-operator.fullname" .}}-external-secret
  data:
    {{- range .Values.vault.secretMappings }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: gslb-operator
        {{- /* test env pulls dnsdist servers from the mock vault entry instead */}}
        {{- if and (eq .secretKey "GSLB_DNSDIST_SERVERS") (eq $.Values.env "test") }}
        property: mock-dnsdist-servers
        {{- else }}
        property: {{ .property }}
        {{- end }}
    {{- end }}
    {{- if .Values.webhooks.enable }}
    {{- range .Values.vault.mqSecretMappings }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: gslb-operator
        property: {{ .property }}
    {{- end }}
    {{- end }}
{{- end }}
