{{- if .Values.vault.enable }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gslb-operator-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gslb-operator-secret-store				
    kind: SecretStore
  target:
    name: gslb-operator-secrets
  data:
    {{- range .Values.vault.secretMappings }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: gslb-operator
        property: {{ .property }}
    {{- end }}
    {{- if .Values.webhooks.enable }}
    {{- range .Values.vault.mqSecretMappings }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: gslb-operator
        property: {{ .property }}
    {{- end }}
    {{- end }}
{{- end }}
